language: clojure
lein: lein2
script: 
  - git clone https://github.com/json-ld/tests json-ld-tests
  - lein2 test!
  - lein2 eastwood
branches:
  only:
    - master
    - dev
jdk:
  - oraclejdk7
notifications:
  hipchat:
    rooms:
      - ec1ead2b384476ea5bcb232b5bb9b6@Snooty Monkey